# Default parameters for jobs
__default__:
  threads: 1
  vmem: 4G

# parameters specific to CCS
ccs:
  threads: "{threads}"
  vmem: 6G

# Parameters for barcoding
barcoding:
  threads: "{threads}"
  vmem: 2G
