# Pipeline Configuration

# Flag to indicate which platform the data was sequenced on
# SEQUENCING_PLATFORM must be either RS2 or SEQUEL
SEQUENCING_PLATFORM: RS2

# Path to the folders which contain the sequencing output for each cell
SOURCE_DATA_PATHS:
  - /exports/lgtc/equipment/PacBio/rundata/RV-100317_230/A01_1/Analysis_Results 

# Path to barcode fasta file used for demultiplexing
BARCODES: /exports/lgtc/equipment/PacBio/jobs/000/000206/pacbio-barcodes/barcodes_pacbio_pad_index_1_9_v2/sequence/barcodes_pacbio_pad_index_1_9_v2.fasta  

# params for individual stages
# to disable a stage, remove its parameters
STAGE_PARAMS:
  CCS:
    minLength: 6000
    maxLength: 7000
    minPasses: 1
    minPredictedAccuracy: 0.75
    numThreads: 1
 
  LIMA:
    same: True           # symmetric barcoding
    num-threads: 4       # number of threads
    dump-clips: True     # save the clipped adapters
    

