channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.5
  - snakemake-minimal=5.3.0
  - pip:
    - "git+ssh://git@git.lumc.nl/PharmacogenomicsPipe/pipe_helper.git@master#egg=pipe_helper"
